"""Inter-agent communication protocols (PRP / A2A-style messages)."""
from .messages import AgentMessage, MessageKind, RepairRequest
from .prp import (
    BriefingEntry,
    CampaignBrief,
    CampaignPlan,
    Dialogue,
    Diary,
    FsmGraph,
    FsmState,
    FsmTransition,
    GeneratedArtifact,
    GenerationResult,
    MissionBlueprint,
    MissionBrief,
    QAFinding,
    QAReport,
    Severity,
    TransitionKind,
    UnitPlacement,
    Waypoint,
)

__all__ = [
    "AgentMessage",
    "MessageKind",
    "RepairRequest",
    "BriefingEntry",
    "CampaignBrief",
    "CampaignPlan",
    "Dialogue",
    "Diary",
    "FsmGraph",
    "FsmState",
    "FsmTransition",
    "GeneratedArtifact",
    "GenerationResult",
    "MissionBlueprint",
    "MissionBrief",
    "QAFinding",
    "QAReport",
    "Severity",
    "TransitionKind",
    "UnitPlacement",
    "Waypoint",
]
