"""briefing.sqf generation — diary entries + BIS_fnc_taskCreate calls."""
from __future__ import annotations

from ..protocols import MissionBlueprint


def generate_briefing_sqf(blueprint: MissionBlueprint) -> str:
    """Generates a JIP-safe briefing.sqf.

    Diary records are added with `player createDiaryRecord`; tasks are created
    via the modular task framework (`BIS_fnc_taskCreate` + `BIS_fnc_taskSetState`).
    """
    out: list[str] = [
        "// Auto-generated by arma3-builder — runs on each client (initPlayerLocal hook).",
        "if (!hasInterface) exitWith {};",
        "waitUntil { !isNull player };",
        "",
    ]

    for entry in blueprint.diary.entries:
        title = _sqf_str(entry.title)
        text = _sqf_str(entry.text)
        out.append(
            f'player createDiaryRecord ["Diary", ["{title}", "<br/>{text}"]];'
        )
    out.append("")

    out.append("// --- Tasks ---")
    for task in blueprint.diary.tasks:
        tid = task.get("id", "task1")
        title = _sqf_str(task.get("title", "Task"))
        desc = _sqf_str(task.get("description", ""))
        marker = task.get("marker", "")
        state = task.get("state", "ASSIGNED")
        out.append(
            '['
            f'"{tid}", true, ["{desc}", "{title}", "{marker}"], '
            f'objNull, "{state}", -1, true, "", true'
            '] call BIS_fnc_taskCreate;'
        )
    out.append("")
    out.append("true")
    return "\n".join(out)


def _sqf_str(s: str) -> str:
    return s.replace('"', '""').replace("\n", "<br/>").strip()
