"""Mission-level description.ext generation."""
from __future__ import annotations

from ..protocols import MissionBlueprint


def generate_mission_description_ext(
    blueprint: MissionBlueprint,
    *,
    skip_lobby: bool | None = None,
    respawn: str | None = None,
    respawn_delay: int = 8,
) -> str:
    is_coop = blueprint.brief.player_count > 1
    if skip_lobby is None:
        skip_lobby = is_coop
    if respawn is None:
        # Coop → BASE (markers are generated into mission.sqm).
        # SP   → INSTANT (no marker required, restart-on-death disabled).
        respawn = "BASE" if is_coop else "INSTANT"

    end_classes = []
    seen_ends: set[str] = set()
    for state in blueprint.fsm.states:
        if state.is_terminal and state.end_type and state.end_type not in seen_ends:
            end_classes.append(_class_block(state.end_type, state.label))
            seen_ends.add(state.end_type)

    cfg_functions = _cfg_functions_block()
    cfg_sounds = _cfg_sounds_block()
    cfg_radio = _cfg_radio_block(blueprint)
    cfg_identities = _cfg_identities_block(blueprint)

    diary_meta = "\n".join(
        f'        // diary: {e.tab} - {e.title}'
        for e in blueprint.diary.entries
    )

    return (
        f'// Auto-generated by arma3-builder for mission "{blueprint.brief.title}"\n'
        f'class Header\n{{\n'
        f'    gameType = "{"Coop" if is_coop else "SP"}";\n'
        f'    minPlayers = 1;\n'
        f'    maxPlayers = {max(1, blueprint.brief.player_count)};\n'
        f'}};\n\n'
        f'briefingName = "{_sqf_string(blueprint.brief.title)}";\n'
        f'onLoadName = "{_sqf_string(blueprint.brief.title)}";\n'
        f'onLoadMission = "{_sqf_string(blueprint.brief.summary)}";\n'
        f'overviewText = "{_sqf_string(blueprint.brief.summary)}";\n'
        f'author = "arma3-builder";\n'
        f'loadScreen = "";\n'
        f'\n'
        f'respawn = "{respawn}";\n'
        f'respawnDelay = {respawn_delay};\n'
        f'respawnDialog = 1;\n'
        f'enableDebugConsole = 0;\n'
        f'skipLobby = {1 if skip_lobby else 0};\n'
        f'disableRandomization[] = {{}};\n'
        f'corpseManagerMode = 1;\n'
        f'corpseLimit = 15;\n'
        f'corpseRemovalMaxTime = 600;\n'
        f'corpseRemovalMinTime = 120;\n'
        f'wreckManagerMode = 1;\n'
        f'wreckLimit = 8;\n'
        f'wreckRemovalMaxTime = 600;\n'
        f'\n'
        f'// Diary entries — registered programmatically in briefing.sqf\n'
        f'{diary_meta}\n'
        f'\n'
        f'{cfg_functions}\n'
        f'\n'
        f'{cfg_sounds}\n'
        f'\n'
        f'{cfg_radio}\n'
        f'\n'
        f'{cfg_identities}\n'
        f'\n'
        f'class CfgDebriefing\n{{\n'
        + "\n".join(end_classes)
        + '\n};\n'
    )


def _class_block(end_type: str, title: str) -> str:
    is_win = end_type != "loser"
    colour = "{0.0, 0.3, 0.6, 1}" if is_win else "{0.6, 0.0, 0.0, 1}"
    return (
        f'    class {end_type}\n'
        f'    {{\n'
        f'        title = "{_sqf_string(title)}";\n'
        f'        subtitle = "";\n'
        f'        description = "{_sqf_string(title)}";\n'
        f'        pictureBackground = "";\n'
        f'        picture = "";\n'
        f'        pictureColor[] = {colour};\n'
        f'    }};'
    )


def _cfg_functions_block() -> str:
    return (
        'class CfgFunctions\n'
        '{\n'
        '    class A3B\n'
        '    {\n'
        '        tag = "A3B";\n'
        '        class core\n'
        '        {\n'
        '            file = "functions";\n'
        '            class initFsm        { preInit = 1; };\n'
        '            class registerTasks  { preInit = 1; };\n'
        '            class repairLoop     { };\n'
        '            class saveProgress   { };\n'
        '            class loadProgress   { };\n'
        '            class playDialog     { };\n'
        '        };\n'
        '    };\n'
        '};'
    )


def _cfg_sounds_block() -> str:
    return (
        'class CfgSounds\n'
        '{\n'
        '    sounds[] = {};\n'
        '};'
    )


def _cfg_radio_block(blueprint: MissionBlueprint) -> str:
    """Emit an empty CfgRadio container — dialog.py fills it when lines exist."""
    return 'class CfgRadio\n{\n    sounds[] = {};\n};'


def _cfg_identities_block(blueprint: MissionBlueprint) -> str:
    """Emit named characters with consistent face/voice so briefings feel curated."""
    named = [u for u in blueprint.units if u.name and not u.is_player]
    if not named:
        return 'class CfgIdentities\n{\n};'
    faces = ["WhiteHead_01", "WhiteHead_02", "AsianHead_A3_02", "AfricanHead_01"]
    voices = ["Male01ENG", "Male02ENG", "Male03ENG", "Male04ENG", "Male05ENG"]
    blocks = []
    for i, u in enumerate(named):
        blocks.append(
            f'    class A3B_{u.name}\n'
            f'    {{\n'
            f'        name = "{_sqf_string(u.name)}";\n'
            f'        face = "{faces[i % len(faces)]}";\n'
            f'        glasses = "None";\n'
            f'        speaker = "{voices[i % len(voices)]}";\n'
            f'        pitch = 1.0;\n'
            f'    }};'
        )
    return 'class CfgIdentities\n{\n' + "\n".join(blocks) + '\n};'


def _sqf_string(s: str) -> str:
    return s.replace('"', '""').replace("\n", " ").strip()
