"""Mission-level description.ext generation."""
from __future__ import annotations

from ..protocols import MissionBlueprint


def generate_mission_description_ext(
    blueprint: MissionBlueprint,
    *,
    skip_lobby: bool = True,
    respawn: str = "BASE",
    respawn_delay: int = 8,
) -> str:
    end_classes = []
    for state in blueprint.fsm.states:
        if state.is_terminal and state.end_type:
            end_classes.append(_class_block(state.end_type, state.label))

    cfg_functions = _cfg_functions_block(blueprint)
    cfg_sounds = _cfg_sounds_block()

    diary_meta = "\n".join(
        f'        // diary: {e.tab} - {e.title}'
        for e in blueprint.diary.entries
    )

    return (
        f'// Auto-generated by arma3-builder for mission "{blueprint.brief.title}"\n'
        f'class Header\n{{\n'
        f'    gameType = "Coop";\n'
        f'    minPlayers = 1;\n'
        f'    maxPlayers = {max(1, blueprint.brief.player_count)};\n'
        f'}};\n\n'
        f'briefingName = "{_sqf_string(blueprint.brief.title)}";\n'
        f'onLoadName = "{_sqf_string(blueprint.brief.title)}";\n'
        f'onLoadMission = "{_sqf_string(blueprint.brief.summary)}";\n'
        f'overviewText = "{_sqf_string(blueprint.brief.summary)}";\n'
        f'author = "arma3-builder";\n'
        f'loadScreen = "";\n'
        f'\n'
        f'respawn = "{respawn}";\n'
        f'respawnDelay = {respawn_delay};\n'
        f'disabledAI = 1;\n'
        f'enableDebugConsole = 0;\n'
        f'skipLobby = {1 if skip_lobby else 0};\n'
        f'corpseManagerMode = 1;\n'
        f'corpseLimit = 15;\n'
        f'corpseRemovalMaxTime = 600;\n'
        f'corpseRemovalMinTime = 120;\n'
        f'wreckManagerMode = 1;\n'
        f'wreckLimit = 8;\n'
        f'wreckRemovalMaxTime = 600;\n'
        f'\n'
        f'// Diary entries — registered programmatically in briefing.sqf\n'
        f'{diary_meta}\n'
        f'\n'
        f'{cfg_functions}\n'
        f'\n'
        f'{cfg_sounds}\n'
        f'\n'
        f'class CfgDebriefing\n{{\n'
        + "\n".join(end_classes)
        + '\n};\n'
    )


def _class_block(end_type: str, title: str) -> str:
    return (
        f'    class {end_type}\n'
        f'    {{\n'
        f'        title = "{_sqf_string(title)}";\n'
        f'        subtitle = "";\n'
        f'        description = "{_sqf_string(title)}";\n'
        f'        pictureBackground = "";\n'
        f'        picture = "";\n'
        f'        pictureColor[] = {{0.0, 0.3, 0.6, 1}};\n'
        f'    }};'
    )


def _cfg_functions_block(blueprint: MissionBlueprint) -> str:
    """Pre-compile mission-local functions instead of execVM."""
    return (
        'class CfgFunctions\n'
        '{\n'
        '    class A3B\n'
        '    {\n'
        '        tag = "A3B";\n'
        '        class core\n'
        '        {\n'
        '            file = "functions";\n'
        '            class initFsm { preInit = 1; };\n'
        '            class registerTasks { preInit = 1; };\n'
        '            class repairLoop { };\n'
        '        };\n'
        '    };\n'
        '};'
    )


def _cfg_sounds_block() -> str:
    return (
        'class CfgSounds\n'
        '{\n'
        '    sounds[] = {};\n'
        '};'
    )


def _sqf_string(s: str) -> str:
    return s.replace('"', '""').replace("\n", " ").strip()
